# Proxy configurations for Rust API Gateway
proxies:
  - id: "api-service-1"
    name: "API Service 1"
    listen_path: "/api/v1"
    backend_protocol: "http"
    backend_host: "localhost"
    backend_port: 8001
    backend_path: "/internal/api"
    strip_listen_path: true
    preserve_host_header: false
    backend_connect_timeout_ms: 3000
    backend_read_timeout_ms: 30000
    backend_write_timeout_ms: 30000
    
  - id: "web-service"
    name: "Web Service"
    listen_path: "/web"
    backend_protocol: "http"
    backend_host: "localhost"
    backend_port: 8002
    strip_listen_path: true
    
  - id: "wildcard-service"
    name: "Wildcard Service"
    listen_path: "/service/:id"
    backend_protocol: "http"
    backend_host: "localhost"
    backend_port: 8003
    backend_path: "/internal/service"
    
  - id: "https-test"
    name: "HTTPS Test Service"
    listen_path: "/https-test"
    backend_protocol: "https"
    backend_host: "httpbin.org"
    backend_port: 443
    backend_path: "/get"
    strip_listen_path: true
    preserve_host_header: false
    backend_connect_timeout_ms: 5000
    backend_read_timeout_ms: 30000
    backend_write_timeout_ms: 30000
